
//This file should be called F_gait.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_gait.h"

void gait_init_all_vars(monitorvars_gait_t* me, io_gait_t* io, uint64_t ds1, uint64_t dts, uint64_t ss, uint64_t std, uint64_t ds2, uint64_t itm, uint64_t mtt, uint64_t tti) {
	//set any IO vars with default values
	

	
	me->_policy_Matching_state = POLICY_STATE_gait_Matching_init;
	//input policy internal vars
	
	me->x = 0;
	
	me->ds1 = ds1;
	
	me->dts = dts;
	
	me->ss = ss;
	
	me->std = std;
	
	me->ds2 = ds2;
	
	me->itm = itm;
	
	me->mtt = mtt;
	
	me->tti = tti;
	
	
}

void gait_run_via_monitor(monitorvars_gait_t* me, io_gait_t* io) {
	gait_run(io);

	//run policies in specified order
	gait_run_monitor_Matching(me, io);
	
}



//output policies

//POLICY Matching BEGIN
//This will run the monitor for gait's policy Matching
void gait_run_monitor_Matching(monitorvars_gait_t* me, io_gait_t* io) {
	//advance timers
	
	me->x++;

	//select transition to advance state
	switch(me->_policy_Matching_state) {
		case POLICY_STATE_gait_Matching_init:
			
			if(io->np == 1) {
				//transition init -> initial_contact on np = 1
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_contact;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 2) {
				//transition init -> loading_response on np = 2
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_loading_response;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 3) {
				//transition init -> mid_stance on np = 3
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_stance;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 4) {
				//transition init -> terminal_stance on np = 4
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_stance;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 5) {
				//transition init -> pre_swing on np = 5
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_pre_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 6) {
				//transition init -> initial_swing on np = 6
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 7) {
				//transition init -> mid_swing on np = 7
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			if(io->np == 8) {
				//transition init -> terminal_swing on np = 8
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_init must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_initial_contact:
			
			if(me->x < me->ds1 && io->np == 1) {
				//transition initial_contact -> initial_contact on x < ds1 and np = 1
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_contact;
				//set expressions
				
				break;
			} 
			if(me->x >= me->ds1 && io->np == 2) {
				//transition initial_contact -> loading_response on x >= ds1 and np = 2
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_loading_response;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_initial_contact must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_loading_response:
			
			if(me->x < me->dts && io->np == 2) {
				//transition loading_response -> loading_response on x < dts and np = 2
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_loading_response;
				//set expressions
				
				break;
			} 
			if(me->x >= me->dts && io->np == 3) {
				//transition loading_response -> mid_stance on x >= dts and np = 3
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_stance;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_loading_response must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_mid_stance:
			
			if(me->x < me->ss && io->np == 3) {
				//transition mid_stance -> mid_stance on x < ss and np = 3
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_stance;
				//set expressions
				
				break;
			} 
			if(me->x >= me->ss && io->np == 4) {
				//transition mid_stance -> terminal_stance on x >= ss and np = 4
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_stance;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_mid_stance must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_terminal_stance:
			
			if(me->x < me->std && io->np == 4) {
				//transition terminal_stance -> terminal_stance on x < std and np = 4
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_stance;
				//set expressions
				
				break;
			} 
			if(me->x >= me->std && io->np == 5) {
				//transition terminal_stance -> pre_swing on x >= std and np = 5
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_pre_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_terminal_stance must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_pre_swing:
			
			if(me->x < me->ds2 && io->np == 5) {
				//transition pre_swing -> pre_swing on x < ds2 and np = 5
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_pre_swing;
				//set expressions
				
				break;
			} 
			if(me->x >= me->ds2 && io->np == 6) {
				//transition pre_swing -> initial_swing on x >= ds2 and np = 6
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_pre_swing must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_initial_swing:
			
			if(me->x < me->itm && io->np == 6) {
				//transition initial_swing -> initial_swing on x < itm and np = 6
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_swing;
				//set expressions
				
				break;
			} 
			if(me->x >= me->itm && io->np == 7) {
				//transition initial_swing -> mid_swing on x >= itm and np = 7
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_initial_swing must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_mid_swing:
			
			if(me->x < me->mtt && io->np == 7) {
				//transition mid_swing -> mid_swing on x < mtt and np = 7
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_mid_swing;
				//set expressions
				
				break;
			} 
			if(me->x >= me->mtt && io->np == 8) {
				//transition mid_swing -> terminal_swing on x >= mtt and np = 8
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_swing;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_mid_swing must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_terminal_swing:
			
			if(me->x < me->tti && io->np == 8) {
				//transition terminal_swing -> terminal_swing on x < tti and np = 8
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_terminal_swing;
				//set expressions
				
				break;
			} 
			if(me->x >= me->tti && io->np == 1) {
				//transition terminal_swing -> initial_contact on x >= tti and np = 1
				me->_policy_Matching_state = POLICY_STATE_gait_Matching_initial_contact;
				//set expressions
				
				me->x = 0;
				break;
			} 
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_terminal_swing must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_gait_Matching_mismatch:
			
			me->_policy_Matching_state = POLICY_STATE_gait_Matching_mismatch;
			//ensure a transition was taken in this state
			//assert(false && "gait_Matching_mismatch must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}
}

//OUTPUT POLICY  END


 
//This function is provided in "F_gait.c"
//It will check the state of the monitor monitor code
//It returns one of the following:
//0: always true (safe)
//1: currently true (safe)
//2: currently false (unsafe)
//3: always false (unsafe)
uint8_t gait_check_rv_status_Matching(monitorvars_gait_t* me) { 
	switch(me->_policy_Matching_state) { 
		case POLICY_STATE_gait_Matching_init:
			  return 0; 
		case POLICY_STATE_gait_Matching_initial_contact:
			  return 0; 
		case POLICY_STATE_gait_Matching_loading_response:
			  return 0; 
		case POLICY_STATE_gait_Matching_mid_stance:
			  return 0; 
		case POLICY_STATE_gait_Matching_terminal_stance:
			  return 0; 
		case POLICY_STATE_gait_Matching_pre_swing:
			  return 0; 
		case POLICY_STATE_gait_Matching_initial_swing:
			  return 0; 
		case POLICY_STATE_gait_Matching_mid_swing:
			  return 0; 
		case POLICY_STATE_gait_Matching_terminal_swing:
			  return 0; 
		case POLICY_STATE_gait_Matching_mismatch:
			  return 3; 
		
	}
}

